// Generated by CoffeeScript 1.8.0
(function() {
  var bl, http, _query;

  http = require('http');

  bl = require('bl');

  module.exports = {
    recommend: function(cb) {
      return _query('/recommendation', cb);
    },
    lmdb: function(cb) {
      return _query('/lmdb', cb);
    }
  };

  _query = function(path, cb) {
    var options, req;
    console.log('yo');
    options = {
      hostname: 'localhost',
      port: 8080,
      path: '/WiseCat/rest/v1/private' + path,
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded'
      }
    };
    return req = http.get(options, function(res) {
      return res.pipe(bl(cb));
    });
  };

}).call(this);
