// Generated by CoffeeScript 1.8.0
(function() {
  var bl, http, _query;

  http = require('http');

  bl = require('bl');

  module.exports = {
    autocomplete: function(text, cb) {
      return _query({
        title: text,
        limit: 3
      }, cb);
    },
    data: function(text, cb) {
      return _query({
        title: text
      }, cb);
    }
  };


  /*
   * Query
   * 
   * La fonction permettant d'executer une requête (HTML GET) sur le service de OMDb
   */

  _query = function(params, cb) {
    var getParams, key, options, req, val;
    getParams = '';
    for (key in params) {
      val = params[key];
      getParams += key + '=' + encodeURI(val) + '&';
    }
    options = {
      hostname: 'www.myapifilms.com',
      path: '/imdb?' + getParams,
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded'
      }
    };
    return req = http.get(options, function(res) {
      return res.pipe(bl(cb));
    });
  };

}).call(this);
